// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tazhoejnahcrijmwbslm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhemhvZWpuYWhjcmlqbXdic2xtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzU4MTAsImV4cCI6MjA3MTcxMTgxMH0.UCsQcfRYQWJ3WCn9dL_CExLfToFcq8NgtEmHiIvNRJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});